name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          [
            'pnpm lint',
            'pnpm format:check',
            'pnpm typecheck',
            'pnpm test',
            'pnpm sheriff',
            'pnpm knip',
            'pnpm --filter react-use-hook-kit run build',
            'pnpm --filter react-use-hook-kit run test:attw',
            'pnpm --filter react-use-hook-kit run test:publint',
            'pnpm --filter @repo/compat-react-17 run test',
            'pnpm --filter @repo/compat-react-18 run test',
            'pnpm --filter @repo/compat-react-19 run test',
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build Package
        run: pnpm --filter react-use-hook-kit run build

      - name: Run command
        run: ${{ matrix.command }}
